[project]
license = {file = "LICENSE"}
classifiers = [
    "Programming Language :: Python :: 3",
    "License :: OSI Approved :: MIT License",
    "Operating System :: OS Independent",
]

[tool.black]
target-version = ['py36']
exclude = '.*\.ipynb'

[tool.isort]
py_version = 36
include_trailing_comma = "true"
line_length = 88
multi_line_output = 3
